package com.sample.rules;

import javax.swing.*;

declare Question
    question: String;
    answers: String[]
end


declare Answer
    question: String;
    answer: String
end

declare addInfo
	info: String
end



function Answer showWindow(Question question) {
    int nr = JOptionPane.showOptionDialog(
            null,
            question.getQuestion(),
            "Question",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.PLAIN_MESSAGE,
            null,
            question.getAnswers(),
            null
    );
    if (nr < 0) {
        return new Answer(question.getQuestion(), "");
    }
    Answer ans = new Answer(question.getQuestion(), question.getAnswers()[nr]);
    return ans;
}

rule "Start"
when
then
    Question question = new Question("Should you be an engineer?", new String[]{"OK"});
    insert(showWindow(question));
    System.out.println("START");
end
//left side
rule "Responsible"
	when
		Answer(question == "Should you be an engineer?" && answer == "OK")
	then
	Question question = new Question("Do you want a responsible job?",new String[] {"Yes", "No"});
	insert(showWindow(question));
end

rule "Marks 60"
when
		Answer(question == "Do you want a responsible job?" && answer == "Yes") 
	then
	Question question = new Question("Marks higher than 60?",new String[] {"Yes", "No"});
	insert(showWindow(question));
end

rule "Willing to study"
	when
		Answer(question == "Marks higher than 60?" && answer == "Yes") || 
		Answer(question == "Have you done this 40 times?" && answer == "No")
	then
		Question question = new Question("Willing to study hard?",new String[] {"Yes", "No","Maybe"});
		insert(showWindow(question));
end

rule "Schooling"
	when
		Answer(question == "Marks higher than 60?" && answer == "No") 
	then
		
		Question question = new Question("Want further schooling?",new String[] {"Yes", "No"});
		insert(showWindow(question));
end

rule "Technical school"
	when
		Answer(question == "Want further schooling?" && answer == "Yes") 
	then
		Question question = new Question("Go to technical school.",new String[] {"OK"});
		insert(showWindow(question));
end	

rule "Science after school"
	when 
		Answer(question == "Go to technical school." && answer == "OK") 
	then
		Question question = new Question("Interested in sciences?",new String[] {"Yes","No"});
		insert(showWindow(question));
end	

rule "Outdoor work"
	when
		Answer(question == "Interested in sciences?" && answer == "Yes")
	then
		Question question = new Question("Like outdoor work?",new String[] {"Yes","No"});
		insert(showWindow(question));
end	

rule "Biology"
when
		Answer(question == "Like outdoor work?" && answer == "Yes")
	then
		Question question = new Question("Like biology?",new String[] {"Yes","No"});
		insert(showWindow(question));
end	

rule "Electronics"
when
		Answer(question == "Like outdoor work?" && answer == "No")
	then
		addInfo info = new addInfo("noOutdoor");
		Question question = new Question("Like electronics?",new String[] {"Yes","No"});
		insert(showWindow(question));
		insert(info);
end	



rule "Electronics course"
when
		Answer(question == "Like electronics?" && answer == "Yes") &&
		addInfo(info == "noOutdoor")
	then
		Question question = new Question("Take electronics course.",new String[] {});
		insert(showWindow(question));
end	

rule "Shop"
when
		Answer(question == "Like electronics?" && answer == "No") &&
		addInfo(info == "noOutdoor")
	then
		Question question = new Question("Like working in shop?",new String[] {"Yes","No"});
		insert(showWindow(question));
end	

rule "Shop course"
when
		Answer(question == "Like working in shop?" && answer == "Yes")
	then
		Question question = new Question("Take machine shop course.",new String[] {});
		insert(showWindow(question));
end	

rule "Detail"
when
		Answer(question == "Like working in shop?" && answer == "No")
	then
		Question question = new Question("Does all this detail bug you?",new String[] {"Yes","No"});
		insert(showWindow(question));
end	

rule "Drafting"
when
		Answer(question == "Does all this detail bug you?" && answer == "No")
	then
		Question question = new Question("Like drafting?",new String[] {"Yes","No"});
		insert(showWindow(question));
end

rule "Draft course"
when
		Answer(question == "Like drafting?" && answer == "Yes")
	then
		Question question = new Question("Take drafting course.",new String[] {});
		insert(showWindow(question));
end

rule "Make sense"
when
		Answer(question == "Like drafting?" && answer == "No")
	then
		Question question = new Question("Do these questions make sense?",new String[] {"Yes","No"});
		insert(showWindow(question));
end

rule "Lake"
when
		Answer(question == "Do these questions make sense?" && answer == "No")
	then
		Question question = new Question("Go jump in the lake.",new String[] {});
		insert(showWindow(question));
end

rule "Chemistry"
when
		Answer(question == "Do these questions make sense?" && answer == "Yes")
	then
		addInfo info = new addInfo("chemistry");
		Question question = new Question("Like chemistry?",new String[] {"Yes","No"});
		insert(showWindow(question));
		insert(info);
end

rule "Chemical technology"
when
		Answer(question == "Like chemistry?" && answer == "Yes") &&
		addInfo(info == "chemistry")
	then
		Question question = new Question("Take chemical technology course.",new String[] {});
		insert(showWindow(question));
end

rule "Other options"
when
		Answer(question == "Like chemistry?" && answer == "No")&&
		addInfo(info == "chemistry")
	then
		Question question = new Question("Consult calendar for other options.",new String[] {});
		insert(showWindow(question));
end

rule "Surveying"
when
		Answer(question == "Like biology?" && answer == "No")
	then
		Question question = new Question("Take surveying course.",new String[] {});
		insert(showWindow(question));
end	


		
rule "Hippie"
	when
		Answer(question == "Do you want a responsible job?" && answer == "No") 
	then
		Question question = new Question("Become a hippie.",new String[] {"OK"});
	insert(showWindow(question));
end


rule "Last"
	when
		Answer(question == "Willing to study hard?" && answer == "No")
	then
	Question question = new Question("Will it last?",new String[] {"Yes", "No"});
	insert(showWindow(question));
end

rule "University"
	when
		Answer(question == "Willing to study hard?" && answer == "Yes")
	then
	Question question = new Question("Go to university.",new String[] {"OK"});
	insert(showWindow(question));
end

rule "Work"
	when
		Answer(question == "Willing to study hard?" && answer == "Maybe")
	then
	Question question = new Question("Go to work for a year.",new String[] {"OK"});
	insert(showWindow(question));
end

rule "40 times"
	when
		Answer(question == "Go to work for a year." && answer == "OK")
	then
	Question question = new Question("Have you done this 40 times?",new String[] {"Yes","No"});
	insert(showWindow(question));
end

rule "Pension"
when
		Answer(question == "Have you done this 40 times?" && answer == "Yes")
	then
	Question question = new Question("Collect old age pension.",new String[] {"OK"});
	insert(showWindow(question));
end


rule "Society"
	when
		Answer(question == "Go to university." && answer == "OK")
	then
	Question question = new Question("Do you want to help society?",new String[] {"Yes","No"});
	insert(showWindow(question));
end

rule "Laywer"
	when
		Answer(question == "Do you want to help society?" && answer == "No")
	then
	Question question = new Question("Become a lawyer.",new String[] {"OK"});
	insert(showWindow(question));
end

rule "English or French"
		when
		Answer(question == "Do you want to help society?" && answer == "Yes") ||
		Answer(question == "Take remedial language class." && answer == "OK")
	then
	Question question = new Question("Are you good in English or French?",new String[] {"Yes","No"});
	insert(showWindow(question));
end

rule "Language class"
		when
		Answer(question == "Are you good in English or French?" && answer == "No")
	then
	Question question = new Question("Take remedial language class.",new String[] {"OK"});
	insert(showWindow(question));
end

rule "Rich"
		when
		Answer(question == "Are you good in English or French?" && answer == "Yes")
	then
	Question question = new Question("Want to become rich?",new String[] {"Yes","No"});
	insert(showWindow(question));
end

rule "Cant help"
	when 
		Answer(question == "Want to become rich?" && answer == "Yes") || 
		Answer(question == "You are too unrealistic to be an engineer." && answer == "OK") ||
		Answer(question == "Interested in sciences?" && answer == "No") ||
		Answer(question == "Like biology?" && answer == "Yes") ||
		Answer(question == "Does all this detail bug you?" && answer == "Yes") || 
		Answer(question == "Are you still with us?" && answer == "No") 
		
	then
		Question question = new Question("This flow-sheet can not help you.",new String[] {"OK"});
		insert(showWindow(question));
end

rule "Practical problems"
	when Answer(question == "Want to become rich?" && answer == "No")
	then
		Question question = new Question("Interested in practical problems?",new String[] {"Yes","No"});
		insert(showWindow(question));
end

rule "Statistician"
when 
	Answer(question == "Interested in practical problems?" && answer == "No")
then
	Question question = new Question("Become a statistician.",new String[] {});
	insert(showWindow(question));
end

rule "Endless"
when 
	Answer(question == "Interested in practical problems?" && answer == "Yes")
then
	Question question = new Question("Think these questions are endless?",new String[] {"Yes","No"});
	insert(showWindow(question));
end

rule "Unrealistic"
when 
	Answer(question == "Think these questions are endless?" && answer == "Yes")
then
	Question question = new Question("You are too unrealistic to be an engineer.",new String[] {"OK"});
	insert(showWindow(question));
end

rule "Science"
when 
	Answer(question == "Think these questions are endless?" && answer == "No")
then
	Question question = new Question("Interested in science?",new String[] {"Yes","No"});
	insert(showWindow(question));
end

rule "Interested Mathematics"
when 
	Answer(question == "Interested in science?" && answer == "Yes")
then
	Question question = new Question("Interested in mathematics?",new String[] {"Yes","No"});
	insert(showWindow(question));
end

rule "Biologist" 
when 
	Answer(question == "Interested in mathematics?" && answer == "No")
then
	Question question = new Question("Become a field biologist.",new String[] {});
	insert(showWindow(question));
end

rule "Good mathematics"
when 
	Answer(question == "Interested in mathematics?" && answer == "Yes")
then
	Question question = new Question("Good at mathematics?",new String[] {"Yes","No"});
	insert(showWindow(question));
end

rule "Tech journalist"
when 
	Answer(question == "Good at mathematics?" && answer == "No")
then
	Question question = new Question("Become a technical journalist",new String[] {});
	insert(showWindow(question));
end
rule "Analysing problems"
when 
	Answer(question == "Good at mathematics?" && answer == "Yes")
then
	Question question = new Question("Good at analysing problems?",new String[] {"Yes","No"});
	insert(showWindow(question));
end

rule "App or memory"
when 
	Answer(question == "Good at analysing problems?" && answer == "Yes")
then
	Question question = new Question("Prefer application over memory?",new String[] {"Yes","No"});
	insert(showWindow(question));
end

rule "Research scientist final"
when 
	Answer(question == "Prefer application over memory?" && answer == "No")
then
	Question question = new Question("Become a research scientist.",new String[] {});
	insert(showWindow(question));
end
	
rule "Aptitude"
when 
	Answer(question == "Prefer application over memory?" && answer == "Yes")
then
	Question question = new Question("You have an aptitude for engineering.",new String[] {"OK"});
	insert(showWindow(question));
end	
	
rule "Enroll in college "
when 
	Answer(question == "You have an aptitude for engineering." && answer == "OK")
then
	Question question = new Question("Enroll in college of engineering.",new String[] {"OK"});
	insert(showWindow(question));
end	


rule "Tuition "
when 
	Answer(question == "Enroll in college of engineering." && answer == "OK")
then
	Question question = new Question("Pay tuition fee.",new String[] {"OK"});
	insert(showWindow(question));
end	


rule "Likes math"
when
	Answer(question == "Pay tuition fee." && answer == "OK")
then
	Question question = new Question("Like mathematics a lot?",new String[] {"Yes","No"});
	insert(showWindow(question));
end	

rule "Math electronics"
when
	Answer(question == "Like mathematics a lot?" && answer == "Yes")
then
	Question question = new Question("Like electronics?",new String[] {"Yes","No"});
	insert(showWindow(question));
end	 

rule "4 electrical"
when
	Answer(question == "Like electronics?" && answer == "Yes") &&
	not(addInfo(info == "noOutdoor"))
then
	Question question = new Question("Take 4 years of electrical engineering.",new String[] {"OK"});
	insert(showWindow(question));
end	 

rule "Like chemistry"
when
	Answer(question == "Like electronics?" && answer == "No")
	not(addInfo(info == "noOutdoor"))
then
	Question question = new Question("Like chemistry?",new String[] {"Yes", "No"});
	insert(showWindow(question));
end	 

rule "4 chemical"
when
	Answer(question == "Like chemistry?" && answer == "Yes") &&
	not(addInfo(info == "chemistry"));
then
	Question question = new Question("Take 4 years of chemical engineering.",new String[] {"OK"});
	insert(showWindow(question));
end	

rule "Geology"
	when Answer(question == "Like chemistry?" && answer == "No") && not(addInfo(info == "chemistry")) ||
		 Answer(question == "Like mathematics a lot?" && answer == "No")
	then
		Question question = new Question("Like geology?",new String[] {"Yes","No"});
		insert(showWindow(question));
end

rule "Machinery"
	when 
		Answer(question == "Like geology?" && answer == "No") 
	then
		Question question = new Question("Like working with machinery?",new String[] {"Yes","No"});
		insert(showWindow(question));
end

rule "Agriculture" 
when 
		Answer(question == "Like working with machinery?" && answer == "Yes") 
	then
		Question question = new Question("Interested in agriculture?",new String[] {"Yes","No"});
		insert(showWindow(question));
end

rule "Agricultural engineering"
when 
		Answer(question == "Interested in agriculture?" && answer == "Yes") 
	then
		Question question = new Question("Take 4 years of agricultural engineering.",new String[] {"OK"});
		insert(showWindow(question));
end

rule "Mechanical engineering"
when 
		Answer(question == "Interested in agriculture?" && answer == "No") 
	then
		Question question = new Question("Take 4 years of mechanical engineering.",new String[] {"OK"});
		insert(showWindow(question));
end

rule "Claustrophobia"
	when 
		Answer(question == "Like geology?" && answer == "Yes") 
	then
		Question question = new Question("Suffer from claustrophobia?",new String[] {"Yes","No"});
		insert(showWindow(question));
end

rule "Mining"
	when 
		Answer(question == "Suffer from claustrophobia?" && answer == "No") 
	then
		Question question = new Question("Take 4 years of mining engineering.",new String[] {"OK"});
		insert(showWindow(question));
end

rule "Petroleum"
	when 
		Answer(question == "Suffer from claustrophobia?" && answer == "Yes") 
	then
		Question question = new Question("Take 4 years of petroleum engineering.",new String[] {"OK"});
		insert(showWindow(question));
end


rule "Still with us" 
when 
		Answer(question == "Like working with machinery?" && answer == "No") 
	then
		Question question = new Question("Are you still with us?",new String[] {"Yes","No"});
		insert(showWindow(question));
end

rule "Constructions problems"
when 
		Answer(question == "Are you still with us?" && answer == "Yes") 
	then
		Question question = new Question("Like construction problems?",new String[] {"Yes","No"});
		insert(showWindow(question));
end

rule "Civil"
when 
	Answer(question == "Like construction problems?" && answer == "Yes") 
	then
		Question question = new Question("Take 4 years of civil engineering.",new String[] {"OK"});
		insert(showWindow(question));
end

rule "Calendar"
	when
		Answer(question == "Like construction problems?" && answer == "No") 
	then
		Question question = new Question("Consult calendar for other options.",new String[] {"OK"});
		insert(showWindow(question));
end


rule "Wish"
	when 
		Answer(question == "Take 4 years of electrical engineering." && answer == "OK") ||
		Answer(question == "Take 4 years of chemical engineering." && answer == "OK") ||
		Answer(question == "Take 4 years of agricultural engineering." && answer == "OK") ||
		Answer(question == "Take 4 years of mechanical engineering." && answer == "OK") ||
		Answer(question == "Take 4 years of mining engineering." && answer == "OK") ||
		Answer(question == "Take 4 years of petroleum engineering." && answer == "OK") ||
		Answer(question == "Take 4 years of civil engineering." && answer == "OK") ||
		Answer(question == "Consult calendar for other options." && answer == "OK")  
	then
		Question question = new Question("Wish you hadn't taken engineering?",new String[] {"Yes","No"});
		insert(showWindow(question));
end

rule "Research scientist"
	when
		Answer(question == "Wish you hadn't taken engineering?" && answer == "Yes")  
	then
		Question question = new Question("You are still qualified as a research scientist.",new String[] {});
		insert(showWindow(question));
end	

rule "Graduate studies"
	when
		Answer(question == "Wish you hadn't taken engineering?" && answer == "No")  
	then
		Question question = new Question("Want graduates studies?",new String[] {"Yes","No"});
		insert(showWindow(question));
end	

rule "Administration"
	when
		Answer(question == "Want graduates studies?" && answer == "Yes")  
	then
		Question question = new Question("Likes administration?",new String[] {"Yes","No"});
		insert(showWindow(question));
end	 

rule "Get degree administration"
when
		Answer(question == "Likes administration?" && answer == "Yes")  
	then
		Question question = new Question("Get graduate degree in business administration.",new String[] {"OK"});
		insert(showWindow(question));
end	

rule "Really mathematics"
when
		Answer(question == "Likes administration?" && answer == "No")  
	then
		Question question = new Question("Really, really like mathematics?",new String[] {"Yes","No"});
		insert(showWindow(question));
end	

rule "Other field"
when
		Answer(question == "Really, really like mathematics?" && answer == "No")  
	then
		Question question = new Question("Find some other field of endeavor.",new String[] {});
		insert(showWindow(question));
end	

rule "Get degree engineering"
when
		Answer(question == "Really, really like mathematics?" && answer == "Yes")   
	then
		Question question = new Question("Get graduate degree in business engineering.",new String[] {"OK"});
		insert(showWindow(question));
end	

rule "Teaching"
when 
	Answer(question == "Get graduate degree in business engineering." && answer == "OK") ||   
	Answer(question == "Get graduate degree in business administration." && answer == "OK") 
then
	Question question = new Question("Like teaching?",new String[] {"Yes", "No"});
	insert(showWindow(question));
end	 

rule "Uni professor"
when
	Answer(question == "Like teaching?" && answer == "Yes")   
then
	Question question = new Question("Become university professor.",new String[] {});
	insert(showWindow(question));
end	 

rule "Like research"
when
	Answer(question == "Like teaching?" && answer == "No")   
then
	Question question = new Question("Like research?",new String[] {"Yes","No"});
	insert(showWindow(question));
end	 

rule "Research department"
when
	Answer(question == "Like research?" && answer == "Yes")   
then
	Question question = new Question("Join research department.",new String[] {});
	insert(showWindow(question));
end	 

rule "Like sales"
when
	Answer(question == "Like research?" && answer == "No")   
then
	Question question = new Question("Like sales?",new String[] {"Yes", "No"});
	insert(showWindow(question));
end

rule "Technical representative"
when
	Answer(question == "Like sales?" && answer == "Yes")   
then
	Question question = new Question("Become technical representative.",new String[] {});
	insert(showWindow(question));
end	

rule "Managment"
when
	Answer(question == "Like sales?" && answer == "No")   
then
	Question question = new Question("Like managment?",new String[] {"Yes", "No"});
	insert(showWindow(question));
end	

rule "Technical staff"
when
	Answer(question == "Like managment?" && answer == "No")   
then
	Question question = new Question("Join technical staff.",new String[] {});
	insert(showWindow(question));
end	

rule "Own business"
when
	Answer(question == "Like managment?" && answer == "Yes")   
then
	Question question = new Question("Want your own business?",new String[] {"Yes", "No"});
	insert(showWindow(question));
end	

rule "Production staff"
when
	Answer(question == "Want your own business?" && answer == "No")   
then
	Question question = new Question("Join production staff?",new String[] {});
	insert(showWindow(question));
end	


rule "10 years experience"
when
	Answer(question == "Want your own business?" && answer == "Yes")   
then
	Question question = new Question("Get at least 10 years of experience.",new String[] {"OK"});
	insert(showWindow(question));
end	


rule "Consulting firm"
when
	Answer(question == "Get at least 10 years of experience." && answer == "OK")   
then
	Question question = new Question("Start consulting firm.",new String[] {});
	insert(showWindow(question));
end	

rule "Bother"
	when 
		Answer(question == "This flow-sheet can not help you." && answer == "OK")
	then
		Question question = new Question("Find someone else to bother.",new String[] {"OK"});
		insert(showWindow(question));
end

rule "Go away"
 when
	Answer(question == "Find someone else to bother." && answer == "OK")
then 
	Question question = new Question("Go away!",new String[] {});
		insert(showWindow(question));
end 

rule "Parlament"
	when
		Answer(question == "Become a lawyer." && answer == "OK")
	then
	Question question = new Question("Run for parlament.",new String[] {"OK"});
	insert(showWindow(question));
end
rule "Senate"
	when
		Answer(question == "Run for parlament." && answer == "OK")
	then
	Question question = new Question("Get appointed to senate.",new String[] {"OK"});
	insert(showWindow(question));
end
rule "Stop"
	when
		Answer(question == "Get appointed to senate." && answer == "OK") || 	
		Answer(question == "Collect old age pension." && answer == "OK") ||
		Answer(question == "Become a hippie." && answer == "OK")
	then
	Question question = new Question("Stop.",new String[] {});
	insert(showWindow(question));
end
 
rule "Lucky"
	when
		Answer(question == "Will it last?" && answer == "Yes")
	then
	Question question = new Question("You are luckier than most!",new String[] {"OK"});
	insert(showWindow(question));
end


rule "Continue"
	when
		Answer(question == "You are luckier than most!" && answer == "OK")
	then
	Question question = new Question("Continue as long as you can.",new String[]{});
	insert(showWindow(question));
end


